# -*-shell-script-*-

PROMPT='%/
> '

#
# Search Python files and extract elements (classes or functions), and
# generate a small report.
#
function get_py_elem() {
    cat $2 | grep -E "$1 " | sed -E "s/$1 ([_a-z|A-Z]+).*/\1/g" | sort
}

#
# Search starting current directory and build up a report with
# elements found
#
function report_py_elems() {
    for elem in `find . -name "*.py" -print | sort`
    do
        echo "* $elem"
        regexps=("^class" "^def" "^ +def")
        descs=("Classes" "Functions" "Methods")
        keywords=("class" "function" "method")
        for i in {1..3}
        do
            nelems=`get_py_elem $regexps[$i] $elem | wc -l`
            if [ $nelems -gt 0 ]
            then
                echo -e "\t+ $descs[$i]:"
                for found_element in `get_py_elem $regexps[$i] $elem`
                do
                    echo -e "\t|- $keywords[$i] $found_element"
                done
                echo -e "\t\- Total: $nelems"
            fi
        done
    done 
}

#
# Remove all docker images
#
function rmdki() {
    for a in `docker image ls --format '{{ .ID }}'`
    do
        docker rmi $a
    done
}

# Aliases
alias ll='ls -lpF'
alias l='ll -a'
alias lsdki="docker image ls --format '{{ .ID }}'"
alias emacs='Emacs -nw'
alias gpycls='get_py_elem ^class'
alias gpyfns='get_py_elem ^def'
alias rptpy='report_py_elems'
alias dk=docker
alias dkc='docker compose'

# Homebrew 
alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'

# Path
export PATH=/opt/homebrew/bin:/Applications/Emacs.app/Contents/MacOS:"$PATH"

# NVM stuff
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# GPG stuff
export GPG_TTY=$(tty)

# GCloud cli stuff
source "$(brew --prefix)/share/google-cloud-sdk/path.zsh.inc"
source "$(brew --prefix)/share/google-cloud-sdk/completion.zsh.inc"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

if [ -f ~/.zsh_customizations ]
then
    . ~/.zsh_customizations
fi

if [ -v INSIDE_EMACS ]
then
    echo -e "Starting shell from EMACS\n"
    export EDITOR="emacsclient"
    alias emacs=emacsclient
    alias git='git --no-pager'
fi
