# -*-shell-script-*-

# Calls emacs under the hood
function e() {
    setxkbmap br
    emacs $* &
}

# Calls django manager, if available
function mn(){
    if [ -f manage.py ]
    then
        python manage.py $*
    fi
}

# Stops all running docker containers
function dkstop() {
    for a in `docker ps --format '{{ .ID }}'`
    do
        docker stop $a
        echo "Container $a stopped"
    done
}

alias pipupg='pip install --upgrade pip && pip install wheel'
alias kct=kubectl
alias gitcfg='git config user.name Ronaldo\ Faria\ Lima && git config user.email ronaldo@brazuca.dev'
alias ll='ls -lpF'
alias l='ls -CFa'
alias dkc='docker compose'
alias dk='docker'
alias db=devbox
alias dbr='devbox run'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

