# -*-shell-script-*-

if [ -f $HOME/.bashrc ]
then
    . $HOME/.bashrc
fi

if [ -e /home/ronaldo/.nix-profile/etc/profile.d/nix.sh ]; then . /home/ronaldo/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
