# -*-shell-script-*-

if [ -f $HOME/.bashrc ]
then
    . $HOME/.bashrc
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="/home/ronaldo/.ebcli-virtual-env/executables:$PATH"
